import { useEffect, useMemo, useRef, useState } from 'react';
import { supabase } from './supabase';
import { Activity, Bell, CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, FileText, History, Home, ImagePlus, LogOut, Menu, Pause, Pencil, Pill, Plus, Search, Settings, Trash2, UserRound, UsersRound, X } from 'lucide-react';

type Role='patient'|'companion';
type Med={id:string;patient_id:string;name:string;form:string;dose:string;interval_minutes:number;start_at:string|null;active:boolean;note:string;photo_urls:string[]};
type Dose={id:string;patient_id:string;medication_id:string;scheduled_at:string;confirmed_at:string|null;confirmed_by:string|null;confirmed_role:Role;status:string};
type Profile={id:string;name:string;role:Role};

type Due={med:Med;scheduled:Date;last:Date|null};

const fmtTime=(d:Date)=>d.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});
const fmtDate=(d:Date)=>d.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'});
const diff=(ms:number)=>{if(ms<=0)return 'Agora';const m=Math.floor(ms/60000),h=Math.floor(m/60),mm=m%60;return h?`Em ${h}h${mm?` ${mm}min`:''}`:`Em ${mm}min`};
const intervalLabel=(n:number)=>n%60===0?`A cada ${n/60} hora${n/60===1?'':'s'}`:`A cada ${Math.floor(n/60)}h ${n%60}min`;

function latestConfirmed(m:Med,doses:Dose[]){return doses.filter(d=>d.medication_id===m.id&&d.confirmed_at).sort((a,b)=>+new Date(b.confirmed_at!)-+new Date(a.confirmed_at!))[0]||null}
function dueFor(m:Med,doses:Dose[],now=new Date()):Due|null{if(!m.active||!m.start_at)return null;const last=latestConfirmed(m,doses);const scheduled=last?new Date(new Date(last.confirmed_at!).getTime()+m.interval_minutes*60000):new Date(m.start_at);return {med:m,scheduled,last:last?new Date(last.confirmed_at!):null}}

export default function App(){
 const [session,setSession]=useState<any>(null),[profile,setProfile]=useState<Profile|null>(null),[patientId,setPatientId]=useState('');
 const [loading,setLoading]=useState(true),[role,setRole]=useState<Role>('patient'),[tab,setTab]=useState<'home'|'meds'|'history'>('home'),[profileOpen,setProfileOpen]=useState(false),[reportOpen,setReportOpen]=useState(false),[reportPeriod,setReportPeriod]=useState<'daily'|'weekly'|'monthly'>('weekly');
 const [meds,setMeds]=useState<Med[]>([]),[doses,setDoses]=useState<Dose[]>([]),[shareCode,setShareCode]=useState(''),[now,setNow]=useState(new Date());
 const [detail,setDetail]=useState<Med|null>(null),[addOpen,setAddOpen]=useState(false),[edit,setEdit]=useState<Med|null>(null),[onboard,setOnboard]=useState(false),[alarm,setAlarm]=useState<Due|null>(null),[done,setDone]=useState<Med|null>(null),[search,setSearch]=useState('');
 const audio=useRef<AudioContext|null>(null),alarmTimer=useRef<any>(null),alarmKey=useRef('');

 useEffect(()=>{supabase.auth.getSession().then(async({data})=>{setSession(data.session);if(data.session)await hydrate(data.session.user.id);setLoading(false)});const {data:l}=supabase.auth.onAuthStateChange(async(_,s)=>{setSession(s);if(s){await hydrate(s.user.id)}else{setProfile(null);setPatientId('');setMeds([]);setDoses([])}});return()=>l.subscription.unsubscribe()},[]);
 useEffect(()=>{const i=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(i)},[]);
 async function hydrate(uid:string){const {data:p}=await supabase.from('profiles').select('*').eq('id',uid).maybeSingle();if(!p){setOnboard(true);return}setProfile(p);setRole(p.role);const {data:mem}=await supabase.from('patient_members').select('patient_id').eq('user_id',uid).limit(1).maybeSingle();if(!mem){setOnboard(true);return}setPatientId(mem.patient_id);setOnboard(false);await loadData(mem.patient_id)}
 async function loadData(pid=patientId){if(!pid)return;const [{data:ms},{data:ds},{data:pt}]=await Promise.all([supabase.from('medications').select('*').eq('patient_id',pid).order('created_at'),supabase.from('dose_events').select('*').eq('patient_id',pid).order('scheduled_at',{ascending:false}),supabase.from('patients').select('share_code').eq('id',pid).single()]);setMeds(ms||[]);setDoses(ds||[]);setShareCode(pt?.share_code||'')}
 const due=useMemo(()=>meds.map(m=>dueFor(m,doses,now)).filter(Boolean) as Due[],[meds,doses,now]);
 const pending=due.filter(x=>x.scheduled.getTime()<=now.getTime()).sort((a,b)=>+a.scheduled-+b.scheduled)[0];
 const upcoming=due.filter(x=>x.scheduled.getTime()>now.getTime()).sort((a,b)=>+a.scheduled-+b.scheduled);
 const next=upcoming[0];
 useEffect(()=>{if(!session||onboard||!pending||alarm||done)return;const k=`${pending.med.id}:${pending.scheduled.toISOString()}`;if(alarmKey.current===k)return;alarmKey.current=k;setAlarm(pending);startAlarm()},[session,onboard,pending?.med.id,pending?.scheduled.getTime(),alarm,done]);
 function startAlarm(){if(!audio.current){try{audio.current=new AudioContext()}catch{return}}const ctx=audio.current;if(ctx.state==='suspended')ctx.resume().catch(()=>{});if(alarmTimer.current)clearInterval(alarmTimer.current);const beep=()=>{try{const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=880;o.type='sine';g.gain.setValueAtTime(.001,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.16,ctx.currentTime+.02);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.35);o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+.36)}catch{}};beep();alarmTimer.current=setInterval(beep,1200);if('Notification'in window&&Notification.permission==='granted'){try{new Notification('Hora do medicamento',{body:pending?.med.name||'Há uma dose pendente'})}catch{}}}
 function stopAlarm(){if(alarmTimer.current)clearInterval(alarmTimer.current);alarmTimer.current=null}
 async function requestNotifications(){if('Notification'in window)await Notification.requestPermission()}
 async function confirmDose(d:Due){stopAlarm();if(!session||!patientId)return;const {data,error}=await supabase.from('dose_events').insert({patient_id:patientId,medication_id:d.med.id,scheduled_at:d.scheduled.toISOString(),confirmed_at:new Date().toISOString(),confirmed_by:session.user.id,confirmed_role:role,status:'confirmed'}).select().single();if(error){alert(error.code==='23505'?'Esta dose já foi registrada.':'Não foi possível registrar a dose.');await loadData();return}setDoses(v=>[data,...v]);setAlarm(null);alarmKey.current='';setDone(d.med)}
 async function snooze(min=10){stopAlarm();alarmKey.current='';setAlarm(null);setTimeout(()=>{const p=due.find(x=>x.med.id===pending?.med.id);if(p)setAlarm(p)},min*60000)}
 async function saveMed(form:any){if(!patientId)return;const payload={patient_id:patientId,name:form.name.trim(),form:form.form||'Medicamento',dose:form.dose.trim(),interval_minutes:Number(form.interval),start_at:form.start||null,active:true,note:form.note||'',photo_urls:String(form.photos||'').split(',').map((x:string)=>x.trim()).filter(Boolean)};const {error}=await supabase.from('medications').insert(payload);if(error)alert(error.message);else{setAddOpen(false);await loadData()}}
 async function updateMed(form:any){if(!edit)return;const {error}=await supabase.from('medications').update({name:form.name.trim(),form:form.form,dose:form.dose,interval_minutes:Number(form.interval),start_at:form.start||null,note:form.note,photo_urls:String(form.photos||'').split(',').map((x:string)=>x.trim()).filter(Boolean),updated_at:new Date().toISOString()}).eq('id',edit.id).eq('patient_id',patientId);if(error)alert(error.message);else{setEdit(null);setDetail(null);await loadData()}}
 async function toggleMed(m:Med){const {error}=await supabase.from('medications').update({active:!m.active,updated_at:new Date().toISOString()}).eq('id',m.id).eq('patient_id',patientId);if(error)alert(error.message);else await loadData()}
 async function removeMed(m:Med){if(!confirm(`Excluir ${m.name}?`))return;const {error}=await supabase.from('medications').delete().eq('id',m.id).eq('patient_id',patientId);if(error)alert(error.message);else{setDetail(null);await loadData()}}
 async function finishOnboarding(r:Role,name:string,code?:string){if(!name.trim())return alert('Informe seu nome.');const {data:{user}}=await supabase.auth.getUser();if(!user)return;if(r==='patient'){const {data,error}=await supabase.rpc('create_patient_for_current_user',{p_name:name});if(error)return alert(error.message);setPatientId(data);setRole(r);setProfile({id:user.id,name,role:r});setOnboard(false);await loadData(data)}else{const {data,error}=await supabase.rpc('join_patient_by_share_code',{p_code:code});if(error)return alert(error.message);await supabase.from('profiles').update({name,role:r}).eq('id',user.id);setPatientId(data);setRole(r);setProfile({id:user.id,name,role:r});setOnboard(false);await loadData(data)}}
 async function google(){const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.origin}});if(error)alert(error.message)}
 async function signIn(email:string,password:string){const {error}=await supabase.auth.signInWithPassword({email,password});if(error)alert(error.message)}
 async function signUp(email:string,password:string,name:string){const {data,error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name}}});if(error)alert(error.message);else if(data.session){}else alert('Conta criada. Verifique seu e-mail para continuar.')}
 if(loading)return <div className="min-h-screen grid place-items-center">Carregando…</div>;
 if(!session)return <Auth onGoogle={google} onSignIn={signIn} onSignUp={signUp}/>;
 if(onboard)return <Onboarding user={session.user} onFinish={finishOnboarding}/>;
 const name=profile?.name||session.user.user_metadata?.full_name||'Usuário';
 return <div className="min-h-screen bg-[#f5f7fb] text-[#182033]">
  <header className="bg-white border-b border-slate-100"><div className="mx-auto max-w-xl px-5 py-5 flex items-center justify-between"><div><div className="text-[10px] font-bold tracking-[.3em] text-slate-400">CONTROLE DE</div><h1 className="text-[28px] font-medium leading-tight">Medicamentos</h1><div className="mt-1 flex gap-1.5 items-center text-sm text-slate-500"><UserRound size={15}/>{name}</div></div><button onClick={()=>setProfileOpen(true)} className="h-12 w-12 rounded-2xl bg-blue-50 grid place-items-center text-blue-600 overflow-hidden">{session.user.user_metadata?.avatar_url?<img src={session.user.user_metadata.avatar_url} className="w-full h-full object-cover"/>:<UserRound/>}</button></div></header>
  <main className="mx-auto max-w-xl px-5 pb-28 pt-5">
   {tab==='home'&&<HomeView name={name} next={next} pending={pending} upcoming={upcoming} now={now} onDetail={setDetail} adherence={adherence(doses)}/>} 
   {tab==='meds'&&<MedsView meds={meds} search={search} setSearch={setSearch} onAdd={()=>setAddOpen(true)} onDetail={setDetail} onPause={toggleMed} onDelete={removeMed}/>} 
   {tab==='history'&&<HistoryView doses={doses} meds={meds}/>} 
  </main>
  <Bottom tab={tab} setTab={setTab}/>
  {profileOpen&&<ProfileDrawer name={name} email={session.user.email||''} role={role} shareCode={shareCode} onClose={()=>setProfileOpen(false)} onReports={()=>{setReportOpen(true);setProfileOpen(false)}} onSettings={requestNotifications} onSignOut={()=>supabase.auth.signOut()}/>} 
  {reportOpen&&<ReportView period={reportPeriod} setPeriod={setReportPeriod} doses={doses} meds={meds} onClose={()=>setReportOpen(false)}/>} 
  {detail&&<DetailSheet med={detail} doses={doses} now={now} canEdit={role==='patient'} onClose={()=>setDetail(null)} onEdit={()=>setEdit(detail)} onPause={()=>toggleMed(detail)} onDelete={()=>removeMed(detail)} onConfirm={()=>{const d=dueFor(detail,doses,now);if(d&&d.scheduled<=now)confirmDose(d)}}/>}
  {addOpen&&<MedForm title="Adicionar medicamento" onClose={()=>setAddOpen(false)} onSave={saveMed}/>} {edit&&<MedForm title="Editar medicamento" med={edit} onClose={()=>setEdit(null)} onSave={updateMed}/>} 
  {alarm&&<AlarmOverlay due={alarm} onConfirm={()=>confirmDose(alarm)} onSnooze={()=>snooze(10)}/>} {done&&<DoneOverlay med={done} onClose={()=>setDone(null)}/>} 
 </div>
}

function adherence(doses:Dose[]){const confirmed=doses.filter(d=>d.confirmed_at);if(!confirmed.length)return 0;const on=confirmed.filter(d=>Math.abs(+new Date(d.confirmed_at!)-+new Date(d.scheduled_at))<=10*60000).length;return Math.round(on/confirmed.length*100)}

function Auth({onGoogle,onSignIn,onSignUp}:{onGoogle:()=>void;onSignIn:(e:string,p:string)=>void;onSignUp:(e:string,p:string,n:string)=>void}){const [mode,setMode]=useState<'login'|'signup'>('login');const [name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState('');return <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-blue-100 p-5 flex items-center justify-center"><div className="w-full max-w-5xl grid md:grid-cols-2 rounded-[32px] overflow-hidden bg-white shadow-soft"><div className="hidden md:flex p-12 bg-gradient-to-br from-blue-700 to-blue-500 text-white relative overflow-hidden"><div className="absolute -right-20 -top-20 w-64 h-64 rounded-full bg-white/10"/><div className="absolute -left-16 bottom-0 w-72 h-72 rounded-full bg-blue-950/20"/><div className="relative self-end"><div className="text-sm tracking-[.28em] uppercase font-bold opacity-70">Controle de Medicamentos</div><h1 className="text-5xl font-semibold mt-3">Cuidar da rotina.<br/>Um horário de cada vez.</h1><p className="mt-5 text-blue-100 max-w-md">Lembretes, registro das doses, histórico e acompanhamento familiar em um só lugar.</p></div></div><div className="p-7 md:p-12"><div className="md:hidden text-xs tracking-[.25em] font-bold text-blue-600">CONTROLE DE MEDICAMENTOS</div><h2 className="text-3xl font-semibold mt-2">{mode==='login'?'Bem-vindo de volta':'Comece agora'}</h2><p className="text-slate-500 mt-2">{mode==='login'?'Entre para continuar seu tratamento.':'Crie sua conta para organizar seus horários.'}</p>{mode==='signup'&&<input className="field mt-7" placeholder="Nome completo" value={name} onChange={e=>setName(e.target.value)}/>}<input className="field mt-4" type="email" placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)}/><input className="field mt-4" type="password" placeholder="Senha" value={password} onChange={e=>setPassword(e.target.value)}/><button className="primary w-full mt-5" onClick={()=>mode==='login'?onSignIn(email,password):onSignUp(email,password,name)}>{mode==='login'?'Entrar':'Criar conta'}</button><div className="flex items-center gap-3 my-6 text-xs text-slate-400"><div className="h-px bg-slate-200 flex-1"/>ou<div className="h-px bg-slate-200 flex-1"/></div><button onClick={onGoogle} className="w-full h-12 rounded-2xl border border-slate-200 font-semibold hover:bg-slate-50">Continuar com Google</button><p className="text-center text-sm text-slate-500 mt-6">{mode==='login'?'Não possui conta?':'Já possui conta?'} <button className="text-blue-600 font-semibold" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'Criar conta':'Entrar'}</button></p></div></div></div>}

function Onboarding({user,onFinish}:{user:any;onFinish:(r:Role,n:string,c?:string)=>void}){const [role,setRole]=useState<Role>('patient'),[name,setName]=useState(String(user.user_metadata?.full_name||user.email?.split('@')[0]||'')),[code,setCode]=useState('');return <div className="min-h-screen grid place-items-center p-5 bg-[#f5f7fb]"><div className="w-full max-w-md bg-white rounded-[28px] p-7 shadow-soft"><div className="w-14 h-14 rounded-2xl bg-blue-50 grid place-items-center text-blue-600"><UserRound/></div><h1 className="text-3xl font-semibold mt-5">Vamos preparar sua conta</h1><p className="text-slate-500 mt-2">Escolha como você vai usar o Controle de Medicamentos.</p><input className="field mt-6" placeholder="Seu nome" value={name} onChange={e=>setName(e.target.value)}/><div className="grid grid-cols-2 gap-3 mt-4"><button onClick={()=>setRole('patient')} className={`role ${role==='patient'?'role-on':''}`}><UserRound/>Paciente</button><button onClick={()=>setRole('companion')} className={`role ${role==='companion'?'role-on':''}`}><UsersRound/>Familiar</button></div>{role==='companion'&&<input className="field mt-4 uppercase" placeholder="Código do paciente (CM-XXXX-XXXX)" value={code} onChange={e=>setCode(e.target.value)}/>}<button className="primary w-full mt-6" onClick={()=>onFinish(role,name,code)}>Continuar</button><p className="text-xs text-slate-400 mt-4 text-center">Novas contas de paciente começam sem medicamentos. Você cadastra apenas os seus.</p></div></div>}

function HomeView({name,next,pending,upcoming,now,onDetail,adherence}:{name:string;next:Due|undefined;pending:Due|undefined;upcoming:Due[];now:Date;onDetail:(m:Med)=>void;adherence:number}){const current=pending||next;return <><section className="blue-card"><div className="text-xs tracking-[.25em] font-bold text-blue-100">{pending?'DOSE PENDENTE':'PRÓXIMA MEDICAÇÃO'}</div><h2 className="text-2xl md:text-3xl font-semibold mt-2 leading-tight">{current?.med.name||'Nenhum horário definido'}</h2>{current?<><div className="flex items-center gap-3 mt-5"><Clock3 size={34}/><span className="text-5xl font-bold">{fmtTime(current.scheduled)}</span></div><div className="font-semibold text-xl mt-4">{diff(current.scheduled.getTime()-now.getTime())}</div><p className="text-blue-100 mt-2">{pending?'Confirme a dose para liberar o próximo horário.':'Você será alertado quando chegar a hora.'}</p></>:<p className="text-blue-100 mt-4">Cadastre seu primeiro medicamento para começar.</p>}</section><div className="flex items-end justify-between mt-7"><h2 className="text-2xl font-semibold flex gap-2 items-center"><CalendarDays size={25}/>Próximos horários</h2></div><div className="space-y-3 mt-4">{upcoming.slice(0,5).map(x=><button key={x.med.id} onClick={()=>onDetail(x.med)} className="card w-full flex items-center text-left"><div className="iconbox"><Clock3/></div><div className="min-w-0 flex-1"><b className="block truncate">{x.med.name}</b><span className="text-sm text-slate-500">{fmtTime(x.scheduled)} · {diff(x.scheduled.getTime()-now.getTime())}</span></div><ChevronRight className="text-slate-300"/></button>)}{!upcoming.length&&<div className="empty">Nenhum próximo horário. Defina o primeiro horário de um medicamento.</div>}</div><div className="card mt-4"><div className="flex items-center justify-between"><div><div className="text-sm text-slate-500">Precisão do tratamento</div><div className="text-3xl font-bold mt-1">{adherence}%</div></div><div className="w-16 h-16 rounded-full bg-blue-50 grid place-items-center text-blue-600"><Activity/></div></div><div className="h-2 bg-slate-100 rounded-full mt-4 overflow-hidden"><div className="h-full bg-blue-600 rounded-full transition-all" style={{width:`${adherence}%`}}/></div><p className="text-xs text-slate-400 mt-2">Baseada no horário programado x horário em que cada dose foi confirmada.</p></div></>}

function MedsView({meds,search,setSearch,onAdd,onDetail,onPause,onDelete}:{meds:Med[];search:string;setSearch:(s:string)=>void;onAdd:()=>void;onDetail:(m:Med)=>void;onPause:(m:Med)=>void;onDelete:(m:Med)=>void}){const list=meds.filter(m=>m.name.toLowerCase().includes(search.toLowerCase()));return <><div className="flex justify-between items-start"><div><div className="eyebrow">SEUS MEDICAMENTOS</div><h2 className="title">Medicamentos</h2><p className="subtitle">Tudo sobre seus tratamentos em um só lugar.</p></div><button className="add" onClick={onAdd}><Plus/></button></div><div className="relative mt-6"><Search className="absolute left-4 top-3.5 text-slate-400" size={20}/><input className="field pl-11" placeholder="Buscar medicamento" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="space-y-3 mt-5">{list.map(m=><div key={m.id} className="card"><button onClick={()=>onDetail(m)} className="w-full flex text-left items-start gap-4"><div className="iconbox"><Pill/></div><div className="flex-1 min-w-0"><b className="text-lg block truncate">{m.name}</b><div className="text-sm text-slate-500 mt-1">{m.dose||'Dose não informada'} · {intervalLabel(m.interval_minutes)}</div><div className="flex gap-2 mt-3"><span className={`badge ${m.active?'green':'gray'}`}>{m.active?'Em uso':'Pausado'}</span><span className="badge gray">{m.form}</span></div></div><ChevronRight className="text-slate-300 mt-1"/></button><div className="border-t border-slate-100 mt-4 pt-3 flex justify-between items-center"><button className="text-sm font-semibold text-blue-600" onClick={()=>onDetail(m)}>Ver detalhes</button><div className="flex gap-2"><button className="small" onClick={()=>onPause(m)}>{m.active?<Pause size={16}/>:<Check size={16}/>} {m.active?'Pausar':'Retomar'}</button><button className="small danger" onClick={()=>onDelete(m)}><Trash2 size={16}/>Excluir</button></div></div></div>)}{!list.length&&<div className="empty">Nenhum medicamento encontrado.</div>}</div></>}

function HistoryView({doses,meds}:{doses:Dose[];meds:Med[]}){return <><div className="eyebrow">ACOMPANHAMENTO</div><h2 className="title">Histórico</h2><p className="subtitle">Veja quando cada dose foi programada e confirmada.</p><div className="space-y-3 mt-6">{doses.slice(0,50).map(d=>{const m=meds.find(x=>x.id===d.medication_id);const delay=d.confirmed_at?Math.round((+new Date(d.confirmed_at)-+new Date(d.scheduled_at))/60000):null;return <div className="card" key={d.id}><div className="flex justify-between gap-4"><div><b>{m?.name||'Medicamento'}</b><div className="text-sm text-slate-500 mt-1">Programado {fmtTime(new Date(d.scheduled_at))} · {fmtDate(new Date(d.scheduled_at))}</div></div><div className={`badge ${delay!==null&&Math.abs(delay)<=10?'green':'amber'}`}>{delay===null?'Pendente':delay<=0?'No horário':`+${delay} min`}</div></div></div>})}{!doses.length&&<div className="empty">Nenhuma dose registrada ainda.</div>}</div></>}

function Bottom({tab,setTab}:{tab:string;setTab:(x:any)=>void}){return <nav className="fixed bottom-0 left-0 right-0 z-30 border-t border-slate-100 bg-white/95 backdrop-blur safe-bottom"><div className="mx-auto max-w-xl grid grid-cols-3 gap-1 p-2"><Nav active={tab==='home'} icon={<Home/>} label="Início" onClick={()=>setTab('home')}/><Nav active={tab==='meds'} icon={<Pill/>} label="Medicamentos" onClick={()=>setTab('meds')}/><Nav active={tab==='history'} icon={<History/>} label="Histórico" onClick={()=>setTab('history')}/></div></nav>}
function Nav({active,icon,label,onClick}:any){return <button onClick={onClick} className={`h-14 rounded-2xl flex flex-col items-center justify-center gap-0.5 ${active?'bg-blue-50 text-blue-600':'text-slate-500'}`}>{icon}<span className="text-[11px] font-semibold">{label}</span></button>}

function ProfileDrawer({name,email,role,shareCode,onClose,onReports,onSettings,onSignOut}:any){return <div className="fixed inset-0 z-50"><button className="absolute inset-0 bg-slate-950/35" onClick={onClose}/><aside className="slide-in absolute right-0 top-0 bottom-0 w-[min(92vw,430px)] bg-[#f7f8fc] p-5 overflow-y-auto"><div className="flex justify-between items-center"><button className="iconbtn" onClick={onClose}><ChevronLeft/></button><h2 className="font-semibold text-xl">Meu perfil</h2><button className="iconbtn" onClick={onClose}><X/></button></div><div className="card mt-6"><div className="flex gap-4 items-center"><div className="avatar"><UserRound/></div><div><b className="text-xl">{name}</b><div className="badge blue mt-2">{role==='patient'?'Paciente':'Familiar'}</div></div></div><div className="mt-5 border-t border-slate-100 pt-4 text-sm text-slate-500 break-all">{email}</div>{role==='patient'&&<div className="mt-4 rounded-2xl bg-blue-50 p-4"><div className="text-xs text-blue-600 font-bold tracking-wider">CÓDIGO FAMILIAR</div><div className="text-xl font-bold text-blue-700 mt-1 tracking-widest">{shareCode}</div></div>}</div><button className="menuitem mt-4" onClick={onReports}><FileText/> <span>Relatórios</span><ChevronRight/></button><button className="menuitem mt-3" onClick={onSettings}><Settings/><span>Configurações do app</span><ChevronRight/></button><button className="menuitem mt-3 text-red-600" onClick={onSignOut}><LogOut/><span>Sair</span></button></aside></div>}

function ReportView({period,setPeriod,doses,meds,onClose}:any){const days=period==='daily'?1:period==='weekly'?7:30;const since=Date.now()-days*86400000;const rows=doses.filter((d:Dose)=>+new Date(d.scheduled_at)>=since);const ok=rows.filter((d:Dose)=>d.confirmed_at&&Math.abs(+new Date(d.confirmed_at)-+new Date(d.scheduled_at))<=10*60000).length;const rate=rows.length?Math.round(ok/rows.length*100):0;return <div className="fixed inset-0 z-50 bg-[#f5f7fb] overflow-y-auto"><div className="mx-auto max-w-xl px-5 py-5"><div className="flex items-center justify-between"><button className="iconbtn" onClick={onClose}><ChevronLeft/></button><h2 className="font-semibold text-xl">Relatórios</h2><div className="w-10"/></div><div className="grid grid-cols-3 gap-2 mt-6">{(['daily','weekly','monthly'] as const).map(p=><button key={p} className={`pill ${period===p?'pill-on':''}`} onClick={()=>setPeriod(p)}>{p==='daily'?'Diário':p==='weekly'?'Semanal':'Mensal'}</button>)}</div><div className="card mt-4"><div className="text-sm text-slate-500">Precisão de uso</div><div className="text-5xl font-bold mt-2 text-blue-600">{rate}%</div><div className="h-3 bg-slate-100 rounded-full mt-5"><div className="h-full bg-blue-600 rounded-full" style={{width:`${rate}%`}}/></div><p className="text-sm text-slate-500 mt-3">{ok} de {rows.length} doses foram confirmadas dentro de uma tolerância de 10 minutos.</p></div><div className="space-y-3 mt-4">{meds.map((m:Med)=>{const r=rows.filter((d:Dose)=>d.medication_id===m.id);return <div className="card" key={m.id}><div className="flex justify-between"><b>{m.name}</b><b className="text-blue-600">{r.length?Math.round(r.filter((d:Dose)=>d.confirmed_at&&Math.abs(+new Date(d.confirmed_at)-+new Date(d.scheduled_at))<=600000).length/r.length*100):0}%</b></div><div className="text-sm text-slate-500 mt-1">{r.length} doses no período</div></div>})}</div></div></div>}

function DetailSheet({med,doses,now,canEdit,onClose,onEdit,onPause,onDelete,onConfirm}:any){const [photo,setPhoto]=useState(0);const photos=med.photo_urls||[];const due=dueFor(med,doses,now);return <div className="fixed inset-0 z-50"><button className="absolute inset-0 bg-slate-950/35" onClick={onClose}/><section className="modal-enter absolute bottom-0 left-0 right-0 max-h-[88vh] overflow-y-auto rounded-t-[30px] bg-white p-6"><div className="mx-auto max-w-xl"><div className="flex justify-between"><div className="eyebrow">DETALHES DO MEDICAMENTO</div><button className="iconbtn" onClick={onClose}><X/></button></div>{photos.length>0&&<div className="relative mt-5 overflow-hidden rounded-3xl bg-slate-100 aspect-[16/8]"><img src={photos[photo]} className="w-full h-full object-cover"/>{photos.length>1&&<><button className="photo prev" onClick={()=>setPhoto((photo-1+photos.length)%photos.length)}><ChevronLeft/></button><button className="photo next" onClick={()=>setPhoto((photo+1)%photos.length)}><ChevronRight/></button><div className="absolute bottom-3 left-0 right-0 flex justify-center gap-1">{photos.map((_:string,i:number)=><span key={i} className={`w-1.5 h-1.5 rounded-full ${i===photo?'bg-white':'bg-white/40'}`}/>)}</div></>}</div>}<div className="flex gap-4 items-center mt-6"><div className="iconbox big"><Pill/></div><div><h2 className="text-2xl font-semibold">{med.name}</h2><p className="text-slate-500">{med.form} · {med.dose||'Dose não informada'}</p></div></div><div className="grid grid-cols-2 gap-3 mt-6"><Info label="Intervalo" value={intervalLabel(med.interval_minutes)}/><Info label="Situação" value={med.active?'Em uso':'Pausado'}/><Info label="Próximo" value={due?fmtTime(due.scheduled):'Defina o horário'}/><Info label="Última dose" value={due?.last?fmtTime(due.last):'Nenhuma'}/></div>{med.note&&<div className="note mt-4"><b>Observações</b><p>{med.note}</p></div>}<div className="grid grid-cols-2 gap-3 mt-5">{due&&due.scheduled<=now&&<button className="primary" onClick={onConfirm}><Check/> Confirmar dose</button>}<button className="secondary" onClick={onPause}>{med.active?<Pause/>:<Check/>}{med.active?'Pausar':'Retomar'}</button>{canEdit&&<button className="secondary" onClick={onEdit}><Pencil/>Editar</button>}</div>{canEdit&&<button className="delete-link" onClick={onDelete}><Trash2/> Excluir medicamento</button>}</div></section></div>}
function Info({label,value}:any){return <div className="info"><span>{label}</span><b>{value}</b></div>}

function MedForm({title,med,onClose,onSave}:any){const [name,setName]=useState(med?.name||''),[form,setForm]=useState(med?.form||'Comprimido'),[dose,setDose]=useState(med?.dose||''),[interval,setInterval]=useState(String(med?.interval_minutes||480)),[start,setStart]=useState(med?.start_at?new Date(med.start_at).toISOString().slice(0,16):''),[note,setNote]=useState(med?.note||''),[photos,setPhotos]=useState((med?.photo_urls||[]).join(', '));return <div className="fixed inset-0 z-50"><button className="absolute inset-0 bg-slate-950/35" onClick={onClose}/><section className="modal-enter absolute bottom-0 left-0 right-0 max-h-[92vh] overflow-y-auto rounded-t-[30px] bg-white p-6"><div className="mx-auto max-w-xl"><div className="flex justify-between"><h2 className="text-xl font-semibold">{title}</h2><button className="iconbtn" onClick={onClose}><X/></button></div><label className="label">Nome<input className="field" value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Cloridrato de moxifloxacino"/></label><div className="grid grid-cols-2 gap-3"><label className="label">Forma<select className="field" value={form} onChange={e=>setForm(e.target.value)}><option>Comprimido</option><option>Colírio</option><option>Cápsula</option><option>Pomada</option><option>Injeção</option><option>Outro</option></select></label><label className="label">Dose<input className="field" value={dose} onChange={e=>setDose(e.target.value)} placeholder="1 comprimido"/></label></div><label className="label">Intervalo (minutos)<input className="field" type="number" min="1" value={interval} onChange={e=>setInterval(e.target.value)}/><span className="hint">Ex.: 120 = a cada 2 horas.</span></label><label className="label">Primeiro horário<input className="field" type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="label">Observações<textarea className="field min-h-24" value={note} onChange={e=>setNote(e.target.value)} placeholder="Orientações importantes..."/></label><label className="label"><span className="flex items-center gap-2"><ImagePlus size={16}/>Fotos (URLs, separadas por vírgula)</span><input className="field" value={photos} onChange={e=>setPhotos(e.target.value)} placeholder="https://...jpg, https://...png"/></label><button className="primary w-full mt-2" onClick={()=>{if(!name.trim()||!start)return alert('Informe o nome e o primeiro horário.');onSave({name,form,dose,interval,start:new Date(start).toISOString(),note,photos})}}>Salvar medicamento</button></div></section></div>}

function AlarmOverlay({due,onConfirm,onSnooze}:any){return <div className="fixed inset-0 z-[70] bg-slate-950/60 grid place-items-center p-5"><div className="w-full max-w-sm bg-white rounded-[32px] p-7 text-center alarm-pulse"><div className="mx-auto w-20 h-20 rounded-3xl bg-blue-50 grid place-items-center text-blue-600"><Bell size={36}/></div><div className="eyebrow mt-6">HORA DO MEDICAMENTO</div><h2 className="text-2xl font-semibold mt-2">{due.med.name}</h2><div className="text-5xl font-bold mt-4">{fmtTime(due.scheduled)}</div><p className="text-slate-500 mt-2">Registre a dose para calcular o próximo horário a partir do momento em que ela foi tomada.</p><button className="primary w-full mt-6" onClick={onConfirm}><Check/> Confirmar dose</button><button className="secondary w-full mt-3" onClick={onSnooze}>Lembrar em 10 min</button></div></div>}
function DoneOverlay({med,onClose}:any){return <div className="fixed inset-0 z-[80] bg-blue-700/95 grid place-items-center p-5 text-white"><div className="text-center max-w-sm"><div className="text-7xl">🎉</div><div className="text-xs tracking-[.3em] font-bold text-blue-200 mt-6">DOSE CONFIRMADA</div><h1 className="text-4xl font-bold mt-2">Muito bem!</h1><p className="text-blue-100 mt-3">{med.name} foi registrada. O próximo horário já foi calculado com base no momento da confirmação.</p><button className="mt-8 rounded-2xl bg-white text-blue-700 px-7 h-12 font-bold" onClick={onClose}>Continuar</button></div></div>}
